export const cardsReference = {
    14: 'black',
    15: 'red',
    'C': 'clubs',
    'D': 'diamonds',
    'H': 'hearts',
    'S': 'spades',
    'J': 'king'
};
export const cards = {
    'AC': { value: 1, suit: 'C' },
    'AD': { value: 1, suit: 'D' },
    'AH': { value: 1, suit: 'H' },
    'AS': { value: 1, suit: 'S' },
    '2C': { value: 2, suit: 'C' },
    '2D': { value: 2, suit: 'D' },
    '2H': { value: 2, suit: 'H' },
    '2S': { value: 2, suit: 'S' },
    '3C': { value: 3, suit: 'C' },
    '3D': { value: 3, suit: 'D' },
    '3H': { value: 3, suit: 'H' },
    '3S': { value: 3, suit: 'S' },
    '4C': { value: 4, suit: 'C' },
    '4D': { value: 4, suit: 'D' },
    '4H': { value: 4, suit: 'H' },
    '4S': { value: 4, suit: 'S' },
    '5C': { value: 5, suit: 'C' },
    '5D': { value: 5, suit: 'D' },
    '5H': { value: 5, suit: 'H' },
    '5S': { value: 5, suit: 'S' },
    '6C': { value: 6, suit: 'C' },
    '6D': { value: 6, suit: 'D' },
    '6H': { value: 6, suit: 'H' },
    '6S': { value: 6, suit: 'S' },
    '7C': { value: 7, suit: 'C' },
    '7D': { value: 7, suit: 'D' },
    '7H': { value: 7, suit: 'H' },
    '7S': { value: 7, suit: 'S' },
    '8C': { value: 8, suit: 'C' },
    '8D': { value: 8, suit: 'D' },
    '8H': { value: 8, suit: 'H' },
    '8S': { value: 8, suit: 'S' },
    '9C': { value: 9, suit: 'C' },
    '9D': { value: 9, suit: 'D' },
    '9H': { value: 9, suit: 'H' },
    '9S': { value: 9, suit: 'S' },
    '10C': { value: 10, suit: 'C' },
    '10D': { value: 10, suit: 'D' },
    '10H': { value: 10, suit: 'H' },
    '10S': { value: 10, suit: 'S' },
    'JC': { value: 11, suit: 'C' },
    'JD': { value: 11, suit: 'D' },
    'JH': { value: 11, suit: 'H' },
    'JS': { value: 11, suit: 'S' },
    'QC': { value: 12, suit: 'C' },
    'QD': { value: 12, suit: 'D' },
    'QH': { value: 12, suit: 'H' },
    'QS': { value: 12, suit: 'S' },
    'KC': { value: 13, suit: 'C' },
    'KD': { value: 13, suit: 'D' },
    'KH': { value: 13, suit: 'H' },
    'KS': { value: 13, suit: 'S' },
    'BJ': { value: 14, suit: 'J' },
    'RJ': { value: 15, suit: 'J' },
};